/* Main.c file generated by New Project wizard
 *
 * Created:   2020
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 	8000000
#include "config.h"

#define RC2 PORTCbits.PINC2
#define _XTAL_FREQ 8000000

#define RD0 PORTDbits.RD0
#define RD1 PORTDbits.RD1
#define RD2 PORTDbits.RD2
#define RD3 PORTDbits.RD3
#define RD4 PORTDbits.RD4
#define RD5 PORTDbits.RD5
#define RD6 PORTDbits.RD6

int DO = 479;
int RE = 451;
int MI = 426;
int FA = 401;
int SOL = 379;
int LA = 358;
int SI = 339;

//Variables globales
int counter = 0; 		//Per indicar quan passin els 8 ms
int increment = 0; 		//Per indicar el increment de CCPR1

void configuracio(){
   CCPTMRS0 = 0x00;
   ANSELC = 0x00;
   INTCONbits.GIE = 1;		//Enables all interrupts
   INTCONbits.PEIE = 1; 	//Enables peripheral interrupts 
   PIE1bits.TMR2IE = 1;		//Enables the TMR2 to PR2 Match Interrupt Enable bit
   PIR1bits.TMR2IF = 0;  
   T2CONbits.T2CKPS1 = 1;   	//Prescaler = 16
   PR2 = 124; 			//PWM period = (PR2 + 1) * 4 * prescaler * TI = (124 + 1) * 4 * 16 * (1/8000000) = 1ms
   CCP1CONbits.CCP1M3 = 1;	//PWM mode
   CCP1CONbits.CCP1M2 = 1;  	//PWM mode
   CCPR1L = 0;			
   CCP1CONbits.DC1B1 = 0;CCP1CONbits.DC1B0 = 0; //Two LSBs of the PWM duty cycle
   T2CONbits.TMR2ON = 1;	//Timer 2 is on
   TRISD = 0xFF;    		 
   PORTD = 0x00;		
   ANSELD = 0x00;
} 

int main(void) {
   configuracio();
   while(1){
      if(RD6) {
	 PR2 = DO;
	 CCPR1L = ((2*(DO + 1))/4);
      }
      if(RD5) {
	 PR2 = RE;
	 CCPR1L = ((2 * (RE+1)) / 4);
      }
      if(RD4) {
	 PR2 = MI;
	 CCPR1L = ((2 * (MI + 1)) / 4);
      }
      if(RD3) {
	 PR2 = FA;
	 CCPR1L = ((2 *(FA + 1)) / 4);
      }
      if(RD2) {
	 PR2 = SOL;
	 CCPR1L = ((2 * (SOL + 1)) / 4);
      }
      if(RD1) {
	 PR2 = LA;
	 CCPR1L = ((2 * (LA + 1)) / 4);
      }
      if(RD0) {
	 PR2 = SI;
	 CCPR1L = ((2 * (SI + 1)) / 4);
      }	 
   }
}

