/* Main.c file generated by New Project wizard
 *
 * Created:   2020
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 8000000  

#include <string.h>
#include "config.h"
#include "GLCD.h"

int nincrement = 0;         	//comptador del increment
int ndecrement = 9;		//comptador del decrement

void main(void) {
   ANSELA = 0;			//PORTA configurat com Digital
   ANSELD = 0;                  //PORTD configurat com Digital
   ANSELB = 0;                  //PORTB configurat com Digital
   PORTA = 0x00;		//Donem uns valors inicials als ports A,D i B
   PORTD = 0x00; 		  
   PORTB = 0x00;
   TRISA = 0xFF;		//PORTA configurat com a entrada
   TRISD = 0x00;		//PORTB configurat com a sortida
   TRISB = 0x00;		//PORTC configurat com a sortida
   GLCDinit();		   	//Inicialitzem la pantalla
   clearGLCD(0,7,0,127);      	//Esborrem pantalla
   setStartLine(0);           	//Definim linia d'inici
   char a0 = '1';		//boleà per controlar l'entrada del bit0 del PORTA
   char a1 = '1';		//boleà per controlar l'entrada del bit1 del PORTA
   char a2 = '1';		//boleà per controlar l'entrada del bit2 del PORTA
   char funcionament1 = '0';    //programa increment en funcionament si funcionament1 == '1'
   char funcionament2 = '0';	//programa decrement en funcionament si funcionament2 == '1'
   char funcionament3 = '0';    //programa decrement en funcionament si funcionament3 == '1'
   char primercop = '0';
   char interrupcio1 = '0';
   
   //button associat al bit 0 PORTA:compte endavant que incrementarà el número que es pinta per pantalla cada segon des de 0 fins a 9.
   //button associat al bit 1 PORTA:compte enrere que decrementarà el número que es pinta per pantalla cada segon des de 9 fins a 0.
   //button associat al bit 2 PORTA:es pintaran tots els números junts.

   while (1) {
      if (PORTAbits.RA0 == 1 && a0 == '1' && funcionament1 == '0') { 
	 nincrement = 0;
	 clearGLCD(0,7,0,127); 		//Esborrem pantalla
	 a0 = '0';
	 funcionament1 = '1';		//posa en marxa el comptador increment
	 funcionament2 = '0';		//para el segon programa (comptador de decrement)
	 funcionament3 = '0';		//para el tercer programa
      }
      if (funcionament1 == '1') {       //comproba si està en marxa el primer programa (increment)
	 writenumbers(2, 55, nincrement);
	 int d = 0; //comptador del delay entra al bucle 1000 vegades fent un delay de 1ms, 1000x1 = 1000ms = 1s
	 while (d < 1000 && PORTAbits.RA1 == 0) { //surt del bucle inmediatament si el bit 1 es posa a 1, ja que es pel flanc ascendent
	    __delay_ms(1);
	    ++d;
	    if (PORTAbits.RA2 == 1 && a2 == '1') { //quan el bit dos es posa a 1 no surtim directament del bucle
		a2 = '0';
		funcionament3 = '1';
		primercop = '1';
	    }
	    if (PORTAbits.RA2 == 0 && funcionament3 == '1') { //aquí es quan sortim del bucle, ja que el botó del bit2 s'activa en el flanc descendent
	       d = 1000;
	    }
	    if (PORTAbits.RA0 == 1 && a0 == '1') { //si rebem un 1 del bit0 parem el programa 1 i sortim del bucle
	       funcionament1 = '0';
	       d = 1000;
	    }
	 }
	 ++nincrement;  //incrementa 1
	 if (nincrement > 9) nincrement = 0;  //Quan n arriba a 9 i torna a sumar 1, torna a començar a comptar desde 0
      }
      if (PORTAbits.RA0 == 0) a0 = '1';
      
      if (PORTAbits.RA1 == 1 && a1 == '1' && funcionament2 == '0') {
	 ndecrement = 9;
	 clearGLCD(0,7,0,127); 		//Esborrem pantalla
	 a1 = '0';
	 funcionament2 = '1';		//posa en marxa el segon programa, associat al botó 1 (decrement)
	 funcionament1 = '0';		//para el primer prorgama (increment)
	 funcionament3 = '0';		//para el tercer programa
      }
      if (funcionament2 == '1') {	//comproba si està en marxa el segon programa (decrement)
	 if (ndecrement >= 0) {
	    writenumbers(2, 55, ndecrement);
	    int d = 0; 	//comptador del delay entra al bucle 1000 vegades fent un delay de 1ms, 1000x1 = 1000ms = 1s
	    while (d < 1000 && PORTAbits.RA0 == 0) { //surt del bucle inmediatament si el bit 0 es posa a 1, ja que es pel flanc ascendent
	       __delay_ms(1);
	       ++d;
	       if (PORTAbits.RA2 == 1 && a2 == '1') { //quan el bit dos es posa a 1 no surtim directament del bucle
		  a2 = '0';
		  funcionament3 = '1';
		  primercop = '1';
	       }
	       if (PORTAbits.RA2 == 0 && funcionament3 == '1') { //aquí es quan sortim del bucle, ja que el botó del bit2 s'activa en el flanc descendent
		  d = 1000;
	       }
	       if (PORTAbits.RA1 == 1 && a1 == '1') { //si rebem un 1 del bit1 parem el programa 2 i sortim del bucle
		  funcionament2 = '0';
		  d = 1000;
	       }
	    }
	    --ndecrement;
	    if (ndecrement < 0) ndecrement = 9;   //quan n arriba a 0 i torna a decrementar una unitat, el comptador es posa a 9 per tornar a decrementar 
	 }
      }
      if (PORTAbits.RA1 == 0) a1 = '1';
      if (PORTAbits.RA2 == 1 && a2 == '1') {    
	  a2 = '0';
	  funcionament3 = '1';  //posa en funcionament el tercer programa
	  primercop = '1';
      }
      if (PORTAbits.RA2 == 0 && funcionament3 == '1') { //comproba si està en marxa el tercer programa
	 funcionament2 = '0';  //para el programa 2
	 funcionament1 = '0';  //para el programa 1 els para en flanc descendent, és a dir, quan bit RA2 = 0
	 a2 = '1';
	 if (primercop == '1') { //la primer vegada esborrem la pantalla
	    clearGLCD(0,7,0,127); 		//Esborrem pantalla
	    primercop = '0';
	 }
	 writenumbers(0, 20, 0); //dibuixa número 0
	 writenumbers(0, 40, 1); //dibuixa número 1
	 writenumbers(0, 60, 2); //dibuixa número 2
	 writenumbers(0, 80, 3); //dibuixa número 3
	 writenumbers(0, 100, 4);//dibuixa número 4
	 writenumbers(4, 20, 5); //dibuixa número 5
	 writenumbers(4, 40, 6); //dibuixa número 6
	 writenumbers(4, 60, 7); //dibuixa número 7
	 writenumbers(4, 80, 8); //dibuixa número 8
	 writenumbers(4, 100, 9);//dibuixa número 9
      }
   }
}