/* Main.c file generated by New Project wizard
 *
 * Created:   2020
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 8000000  

#include <string.h>
#include "config.h"
#include "GLCD.h"

const char s1 = '%';
int unitats = 0;	//unitats del contador
int desenes = 0;	//desenes del contador
int centenes = 0;	//centenes del contador

/*cada cop que es crida a aquesta funció s'incrementa una unitat al contador*/
void count (){   
   ++unitats;
   if (unitats > 9) {
      unitats = 0;
      ++desenes;
   }
   if (desenes > 9) {
      desenes = 0;
      ++centenes;
   }
   if (centenes > 9) {
      centenes = 0;
   }
}

/*aquesta funció escriu el parámetre char que li passem*/
void escriure_beta() {
   putchGLCD(3, 13, s1);
}

/*aquesta funció escriu el contador*/
void pintar() {
   writeNum(3, 10, centenes);
   writeNum(3, 12, desenes);
   writeNum(3, 14, unitats);
}

void main(void) {
   ANSELA = 0;			//PORTA configurat com Digital
   ANSELD = 0;                  //PORTD configurat com Digital
   ANSELB = 0;                  //PORTB configurat com Digital
   PORTA = 0;			//Donem uns valors inicials als ports
   PORTD = 0; 		  
   PORTB = 0;
   TRISA = 0xFF;		//PORTA configurat com a entrada
   TRISD = 0x00;		//PORTB configurat com a sortida
   TRISB = 0x00;		//PORTC configurat com a sortida
   GLCDinit();		   	//Inicialitzem la pantalla
   clearGLCD(0,7,0,127);      	//Esborrem pantalla
   setStartLine(0);           	//Definim linia d'inici
   pintar();			//El contador comença escribint un 0
   char premut = 'f';		//Control entre señals 1 i 0 del bit 0 del PORTA
   char boto = '0';		//Control entre bit 0 i bit 1 del PORTA
   while (1) {
      if (PORTAbits.RA0 == 1 && premut == 't') {
	 clearGLCD(0,7,0,127); 		//Esborrem pantalla
	 count();
	 premut = 'f';
	 pintar();
	 __delay_ms(20);
	 boto = '0';
      }
      if (PORTAbits.RA0 == 0 && boto == '0') {
	 premut = 't';
	 __delay_ms(20);
	 pintar();
      } 
      if (PORTAbits.RA1 == 1) {
	 clearGLCD(0,7,0,127);      	//Esborrem pantalla   
	 escriure_beta();
	 boto = '1';
      }
      if (PORTAbits.RA1 == 0 && boto == '1') {
	 escriure_beta();
      }
   }
}