/* Main.c file generated by New Project wizard
 *
 * Created:   lu. oct. 26 2020
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"

#define _XTAL_FREQ 8000000

unsigned char array[10]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x67}; //numbers from 0 to 9
int count = 0; //counter 

void config(){
   ANSELA = 0; //Digital
   ANSELB = 0; //Digital
   ANSELD = 0; //Digital
   TRISA = 0;  //Output
   TRISB = 1;  //Input
   TRISD = 0;  //Output
   PORTA = 0;  //Initialize PORTA
   PORTD = 0;  //Initialize PORTD
   //about RCON
   RCONbits.IPEN = 1; // enable priority interrupt
   //about INTCON
   INTCONbits.GIEH = 1; // enable all high-priority interrupts
   INTCONbits.GIEL = 1; // enable all low-priority interrupts
   INTCONbits.INT0IE = 1; // enable the INT0 external interrupt
   INTCONbits.INT0IF = 0; // INT0 interrupt did not occur  
   //about INTCON2
   INTCON2bits.INTEDG0 = 0; // INTO on failing edge
   INTCON2bits.INTEDG1 = 1; // INT1 on rising edge
   INTCON2bits.INTEDG2 = 1; // INT2 on rising edge
   //about INTCON3
   INTCON3bits.INT1IP = 0; // INT1 as low priority
   INTCON3bits.INT2IP = 0; // INT2 as low priority
   INTCON3bits.INT1IE = 1; // enable the INT1 external interrupt 
   INTCON3bits.INT2IE = 1; // enable the INT2 exetrnal interrupt
   INTCON3bits.INT1IF = 0; // INT1 interrupt did not occur
   INTCON3bits.INT2IF = 1; // INT2 interrupt did occur, the program starts with the counter as 0 
}

void increment() {
   PORTA = 0xF;
   LATD = array[count];
   __delay_ms(10);
   ++count;
}

void error() {
   for (int i = 0; i < 4; ++i) {
      if(i == 0) {
	 PORTD = 0;
	 PORTA = 0x1;
	 LATD = 0x86;
      }
      else if (i == 1) { 
	 PORTD = 0;
	 PORTA = 0x2;
	 LATD = 0x50;
      }
      else if (i == 2) {
	 PORTD = 0;
	 PORTA = 0x4;
	 LATD = 0x50;
      }
      else {
	 PORTD = 0;
	 PORTA = 0x8;
	 LATD = 0x79;
      }
   }
}

void interrupt high_priority control(void) {
   if (INTCONbits.INT0IF == 1 && INTCONbits.INT0IE == 1) {
      INTCONbits.INT0IF = 0;
      if (INTCONbits.GIEL == 1) {
	 INTCONbits.GIEL = 0;
      }
      else if (INTCONbits.GIEL == 0) {
	 INTCONbits.GIEL = 1;
      }
      if (INTCON3bits.INT1IF == 1) INTCON3bits.INT1IF = 0;
      if (INTCON3bits.INT2IF == 1) INTCON3bits.INT2IF = 0;
   }
}  

void interrupt low_priority sum_and_reset(void) {
   if (INTCON3bits.INT1IF == 1) {
      INTCON3bits.INT1IF = 0;
      if (count < 10) increment();
      else {
	 while(INTCON3bits.INT2IF == 0) {
	    error();
	 }
      }
   }
   else if (INTCON3bits.INT2IF == 1) {
      INTCON3bits.INT2IF = 0;
      count = 0;
      PORTA = 0xF;
      LATD = array[count];
      __delay_ms(10);
      ++count;
   }
} 

void main(void){
   config();
   while(1);
}